# Generated by Django 5.0.4 on 2024-04-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSKsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liked',
            field=models.BooleanField(default=0),
        ),
    ]
